// The "Публикации" module's own endpoint — channels and scheduled/published
// posts for one brand's calendar. Follows the same action-dispatch POST
// shape as api/workspace/route.ts (one endpoint, an `action` field in the
// body) rather than splitting into a REST resource per table, to match how
// every other workspace-scoped write in this codebase already works.
//
// Publish target is always a `generations` row — see the comment on
// `publications` in db/schema.ts for why `materials` (semantics/
// competitors/content-plan) is never a valid target. A row added straight
// from the calendar with pasted text/an external image creates a
// format:"external" generation on the fly; one already generated by KLIO
// (from the generator, an editor, or a content-plan topic) is referenced by
// its existing id instead.

import { and, desc, eq, gte, inArray, lte, sql } from "drizzle-orm";
import { brands, generations, publications, socialChannels } from "../../../db/schema";
import { planRule } from "../../plans";
import { isSocialPlatform, type ChannelCredentials } from "../_lib/publishing-config";
import { describeChannel, socialChannelSummary, ChannelValidationError } from "../_lib/social-channels";
import { attemptPublish } from "../_lib/publish-attempt";
import { resolveBaseUrl } from "../_lib/base-url";
import {
  ensureAccount,
  getWorkspaceDb,
  workspaceDatabaseAvailable,
  workspaceErrorResponse,
  workspaceIdentity,
} from "../_lib/workspace-account";

type PublicationsPayload = {
  action?: unknown;
  brandId?: unknown;
  id?: unknown;
  platform?: unknown;
  telegram?: unknown;
  vk?: unknown;
  generationId?: unknown;
  title?: unknown;
  body?: unknown;
  imageUrl?: unknown;
  channelIds?: unknown;
  channelId?: unknown;
  scheduledAt?: unknown;
};

function clean(value: unknown, maxLength: number) {
  return typeof value === "string" ? value.trim().slice(0, maxLength) : "";
}

function parseIsoDate(value: unknown): string | null {
  const raw = clean(value, 40);
  const time = new Date(raw).getTime();
  return Number.isFinite(time) ? new Date(time).toISOString() : null;
}

async function currentChannelCount(db: Awaited<ReturnType<typeof getWorkspaceDb>>, email: string) {
  const [{ count = 0 } = { count: 0 }] = await db.select({ count: sql<number>`count(*)` }).from(socialChannels).where(eq(socialChannels.ownerEmail, email));
  return Number(count);
}

async function ownedBrand(db: Awaited<ReturnType<typeof getWorkspaceDb>>, brandId: string, email: string) {
  const [brand] = await db.select({ id: brands.id }).from(brands).where(and(eq(brands.id, brandId), eq(brands.ownerEmail, email))).limit(1);
  return brand;
}

function credentialsFromPayload(platform: string, payload: PublicationsPayload): ChannelCredentials {
  if (platform === "telegram") {
    const source = payload.telegram && typeof payload.telegram === "object" ? payload.telegram as Record<string, unknown> : {};
    return { platform: "telegram", telegram: { botToken: clean(source.botToken, 200), chatId: clean(source.chatId, 120) } };
  }
  const source = payload.vk && typeof payload.vk === "object" ? payload.vk as Record<string, unknown> : {};
  return { platform: "vk", vk: { groupId: clean(source.groupId, 40), accessToken: clean(source.accessToken, 300), photoAccessToken: clean(source.photoAccessToken, 300) || undefined } };
}

function publicationResponse(row: typeof publications.$inferSelect, generation: typeof generations.$inferSelect | undefined, channel: typeof socialChannels.$inferSelect | undefined) {
  return {
    id: row.id,
    brandId: row.brandId,
    generationId: row.generationId,
    channelId: row.channelId,
    scheduledAt: row.scheduledAt,
    status: row.status,
    providerPostId: row.providerPostId,
    errorMessage: row.errorMessage,
    retryCount: row.retryCount,
    publishedAt: row.publishedAt,
    title: generation?.title ?? "",
    body: generation?.body ?? "",
    imageUrl: generation?.imageUrl ?? "",
    channel: channel ? socialChannelSummary(channel) : null,
  };
}

export async function GET(request: Request) {
  try {
    if (!await workspaceDatabaseAvailable()) return Response.json({ error: "Хранилище кабинета недоступно." }, { status: 503 });
    const user = await workspaceIdentity();
    const db = await getWorkspaceDb();
    const url = new URL(request.url);
    const brandId = clean(url.searchParams.get("brandId"), 100);
    if (!brandId || !await ownedBrand(db, brandId, user.email)) {
      return Response.json({ error: "Бренд не найден или недоступен." }, { status: 404 });
    }

    // Defaults to a generous ±60-day window around today so a first render
    // with no explicit range still shows something sensible instead of an
    // unbounded table scan.
    const now = Date.now();
    const from = parseIsoDate(url.searchParams.get("from")) ?? new Date(now - 60 * 86_400_000).toISOString();
    const to = parseIsoDate(url.searchParams.get("to")) ?? new Date(now + 60 * 86_400_000).toISOString();

    const channelRows = await db.select().from(socialChannels).where(eq(socialChannels.brandId, brandId)).orderBy(desc(socialChannels.createdAt));
    const publicationRows = await db.select().from(publications).where(and(
      eq(publications.brandId, brandId),
      gte(publications.scheduledAt, from),
      lte(publications.scheduledAt, to),
    )).orderBy(publications.scheduledAt);

    // Composed in application code rather than a SQL join, matching every
    // other multi-table read in this API (see materialResponse in
    // api/workspace/route.ts) — publication counts per brand are small
    // enough that two extra indexed lookups cost nothing next to a join's
    // added complexity.
    const generationIds = [...new Set(publicationRows.map((row) => row.generationId))];
    const generationRows = generationIds.length
      ? await db.select().from(generations).where(inArray(generations.id, generationIds))
      : [];
    const generationById = new Map(generationRows.map((row) => [row.id, row]));
    const channelById = new Map(channelRows.map((row) => [row.id, row]));

    return Response.json({
      channels: channelRows.map(socialChannelSummary),
      publications: publicationRows.map((row) => publicationResponse(row, generationById.get(row.generationId), channelById.get(row.channelId))),
      channelLimit: planRule((await ensureAccount(user)).planId).channelLimit,
    });
  } catch (error) {
    return workspaceErrorResponse(error);
  }
}

export async function POST(request: Request) {
  try {
    if (!await workspaceDatabaseAvailable()) return Response.json({ error: "Хранилище кабинета недоступно." }, { status: 503 });
    const user = await workspaceIdentity();
    const db = await getWorkspaceDb();
    const payload = await request.json() as PublicationsPayload;
    const action = clean(payload.action, 40);
    const account = await ensureAccount(user);

    if (action === "connect_channel") {
      const brandId = clean(payload.brandId, 100);
      if (!brandId || !await ownedBrand(db, brandId, user.email)) {
        return Response.json({ error: "Бренд не найден или недоступен." }, { status: 404 });
      }
      const platform = clean(payload.platform, 20);
      if (!isSocialPlatform(platform)) return Response.json({ error: "Неизвестная площадка." }, { status: 400 });

      const rule = planRule(account.planId);
      const used = await currentChannelCount(db, user.email);
      if (used >= rule.channelLimit) {
        return Response.json({ error: `Тариф «${rule.name}» поддерживает до ${rule.channelLimit} ${rule.channelLimit === 1 ? "канала" : "каналов"} публикации.` }, { status: 409 });
      }

      const credentials = credentialsFromPayload(platform, payload);
      let info: { label: string; avatarUrl: string };
      try {
        info = await describeChannel(credentials);
      } catch (error) {
        if (error instanceof ChannelValidationError) return Response.json({ error: error.message }, { status: 400 });
        throw error;
      }

      const [created] = await db.insert(socialChannels).values({
        id: crypto.randomUUID(),
        ownerEmail: user.email,
        brandId,
        platform,
        label: info.label,
        avatarUrl: info.avatarUrl,
        credentialsJson: JSON.stringify(credentials),
      }).returning();
      return Response.json({ channel: socialChannelSummary(created) }, { status: 201 });
    }

    if (action === "remove_channel") {
      const id = clean(payload.id, 100);
      if (!id) return Response.json({ error: "Не указан канал для отключения." }, { status: 400 });
      const [deleted] = await db.delete(socialChannels).where(and(eq(socialChannels.id, id), eq(socialChannels.ownerEmail, user.email))).returning({ id: socialChannels.id });
      if (!deleted) return Response.json({ error: "Канал не найден или недоступен." }, { status: 404 });
      // Anything still waiting to go out through this channel can never
      // publish now — drop it rather than leave a scheduled row silently
      // pointing at nothing (attemptPublish already handles a missing
      // channel defensively, but a ghost calendar entry is worse UX than
      // just removing it here).
      await db.delete(publications).where(and(eq(publications.channelId, id), eq(publications.status, "scheduled")));
      return Response.json({ ok: true, id: deleted.id });
    }

    if (action === "schedule") {
      const brandId = clean(payload.brandId, 100);
      if (!brandId || !await ownedBrand(db, brandId, user.email)) {
        return Response.json({ error: "Бренд не найден или недоступен." }, { status: 404 });
      }
      const scheduledAt = parseIsoDate(payload.scheduledAt);
      if (!scheduledAt) return Response.json({ error: "Укажите корректные дату и время публикации." }, { status: 400 });

      const channelIds = Array.isArray(payload.channelIds) ? payload.channelIds.filter((item): item is string => typeof item === "string") : [];
      if (!channelIds.length) return Response.json({ error: "Выберите хотя бы один канал." }, { status: 400 });
      const ownedChannels = await db.select().from(socialChannels).where(and(eq(socialChannels.brandId, brandId), inArray(socialChannels.id, channelIds)));
      if (ownedChannels.length !== channelIds.length) return Response.json({ error: "Один из каналов не найден или недоступен." }, { status: 404 });

      let generationId = clean(payload.generationId, 100);
      if (generationId) {
        const [existing] = await db.select({ id: generations.id }).from(generations).where(and(
          eq(generations.id, generationId),
          eq(generations.ownerEmail, user.email),
          eq(generations.brandId, brandId),
        )).limit(1);
        if (!existing) return Response.json({ error: "Материал не найден или недоступен." }, { status: 404 });
      } else {
        // Добавлено вручную прямо из календаря — created outside the
        // generator, so it never touches recordGeneration()/the AI
        // generation quota (mirrors copy_generation/save_material in
        // api/workspace/route.ts, which bypass it for the same reason:
        // no AI call happened here).
        const title = clean(payload.title, 500);
        const body = clean(payload.body, 20_000);
        if (!title && !body) return Response.json({ error: "Добавьте текст публикации." }, { status: 400 });
        const [created] = await db.insert(generations).values({
          id: crypto.randomUUID(),
          ownerEmail: user.email,
          brandId,
          format: "external",
          topic: "",
          title: title || "Без названия",
          body,
          imageUrl: clean(payload.imageUrl, 2000),
        }).returning();
        generationId = created.id;
      }

      const rows = await db.insert(publications).values(channelIds.map((channelId) => ({
        id: crypto.randomUUID(),
        ownerEmail: user.email,
        brandId,
        generationId,
        channelId,
        scheduledAt,
        status: "scheduled" as const,
      }))).returning();

      const generationRow = (await db.select().from(generations).where(eq(generations.id, generationId)).limit(1))[0];
      const channelByIdLocal = new Map(ownedChannels.map((row) => [row.id, row]));
      return Response.json({ publications: rows.map((row) => publicationResponse(row, generationRow, channelByIdLocal.get(row.channelId))) }, { status: 201 });
    }

    if (action === "update") {
      const id = clean(payload.id, 100);
      const [publication] = await db.select().from(publications).where(and(eq(publications.id, id), eq(publications.ownerEmail, user.email))).limit(1);
      if (!publication) return Response.json({ error: "Публикация не найдена или недоступна." }, { status: 404 });

      const nextScheduledAt = payload.scheduledAt !== undefined ? parseIsoDate(payload.scheduledAt) : publication.scheduledAt;
      if (payload.scheduledAt !== undefined && !nextScheduledAt) return Response.json({ error: "Укажите корректные дату и время публикации." }, { status: 400 });
      const nextChannelId = clean(payload.channelId, 100) || publication.channelId;
      if (nextChannelId !== publication.channelId) {
        const [channel] = await db.select({ id: socialChannels.id }).from(socialChannels).where(and(eq(socialChannels.id, nextChannelId), eq(socialChannels.brandId, publication.brandId))).limit(1);
        if (!channel) return Response.json({ error: "Канал не найден или недоступен." }, { status: 404 });
      }

      // Touching the schedule on a "failed" row re-queues it for the cron
      // instead of leaving it stuck failed forever — the natural way a
      // person actually retries is "fix the thing, then move it", not a
      // separate "retry" button they'd have to notice first.
      const reQueue = publication.status === "failed" && (payload.scheduledAt !== undefined || payload.channelId !== undefined);
      await db.update(publications).set({
        scheduledAt: nextScheduledAt ?? publication.scheduledAt,
        channelId: nextChannelId,
        ...(reQueue ? { status: "scheduled" as const, retryCount: 0, errorMessage: null } : {}),
        updatedAt: sql`CURRENT_TIMESTAMP`,
      }).where(eq(publications.id, id));

      if (payload.title !== undefined || payload.body !== undefined || payload.imageUrl !== undefined) {
        const [generation] = await db.select().from(generations).where(and(eq(generations.id, publication.generationId), eq(generations.ownerEmail, user.email))).limit(1);
        if (generation) {
          await db.update(generations).set({
            ...(payload.title !== undefined ? { title: clean(payload.title, 500) || "Без названия" } : {}),
            ...(payload.body !== undefined ? { body: clean(payload.body, 20_000) } : {}),
            ...(payload.imageUrl !== undefined ? { imageUrl: clean(payload.imageUrl, 2000) } : {}),
          }).where(eq(generations.id, generation.id));
        }
      }

      const [updated] = await db.select().from(publications).where(eq(publications.id, id)).limit(1);
      const [generation] = await db.select().from(generations).where(eq(generations.id, updated.generationId)).limit(1);
      const [channel] = await db.select().from(socialChannels).where(eq(socialChannels.id, updated.channelId)).limit(1);
      return Response.json({ publication: publicationResponse(updated, generation, channel) });
    }

    if (action === "delete") {
      const id = clean(payload.id, 100);
      const [deleted] = await db.delete(publications).where(and(eq(publications.id, id), eq(publications.ownerEmail, user.email))).returning({ id: publications.id });
      if (!deleted) return Response.json({ error: "Публикация не найдена или недоступна." }, { status: 404 });
      return Response.json({ ok: true, id: deleted.id });
    }

    if (action === "publish_now") {
      const id = clean(payload.id, 100);
      const [publication] = await db.select({ id: publications.id }).from(publications).where(and(eq(publications.id, id), eq(publications.ownerEmail, user.email))).limit(1);
      if (!publication) return Response.json({ error: "Публикация не найдена или недоступна." }, { status: 404 });
      const workspaceUrl = `${resolveBaseUrl(request)}/workspace`;
      const result = await attemptPublish(id, user.email, workspaceUrl);
      if (!result) return Response.json({ error: "Публикация не найдена или недоступна." }, { status: 404 });
      if (result.status === "failed" || result.status === "scheduled") {
        return Response.json({ error: result.errorMessage, status: result.status }, { status: 502 });
      }
      return Response.json({ status: result.status, providerPostId: result.providerPostId });
    }

    return Response.json({ error: "Неизвестное действие модуля публикаций." }, { status: 400 });
  } catch (error) {
    return workspaceErrorResponse(error);
  }
}
